"""empty message

Revision ID: 8c2d01f5ce1b
Revises: d45751b89214
Create Date: 2023-05-14 21:49:54.453809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2d01f5ce1b'
down_revision = 'd45751b89214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('min_level',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('reorder_level',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('reorder_level',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('min_level',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)

    # ### end Alembic commands ###
