"""empty message

Revision ID: b3e0501e70da
Revises: f76c9a61304c
Create Date: 2023-05-18 08:15:39.088364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e0501e70da'
down_revision = 'f76c9a61304c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_take_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stocktake_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('stock_take_items_stocktake_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'stock_takes', ['stocktake_id'], ['id'])
        batch_op.drop_column('stocktake_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_take_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stocktake_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stock_take_items_stocktake_item_id_fkey', 'stock_takes', ['stocktake_item_id'], ['id'])
        batch_op.drop_column('stocktake_id')

    # ### end Alembic commands ###
