"""empty message

Revision ID: c9889b0b7d4c
Revises: 8c2d01f5ce1b
Create Date: 2023-05-15 14:38:50.482977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9889b0b7d4c'
down_revision = '8c2d01f5ce1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
