"""empty message

Revision ID: f76c9a61304c
Revises: de12e10cc2b9
Create Date: 2023-05-17 15:46:59.776374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76c9a61304c'
down_revision = 'de12e10cc2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_takes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_take_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('stocktake_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['stocktake_item_id'], ['stock_takes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_take_items')
    op.drop_table('stock_takes')
    # ### end Alembic commands ###
